apiVersion: batch/v1
kind: Job
metadata:
  name: ledger-account-plan
spec:
  template:
    metadata:
      labels:
        run: ledger-account-plan
    spec:
      restartPolicy: Never
      containers:
        - name: ledger
          image: docker.io/mikebookhamcap/ledger:1.0.8
          imagePullPolicy: Always
          args:
            [
              "@/cnb/process/config/commands.txt",
              "--spring.datasource.url=jdbc:postgresql://cockroachdb-public.uksouth.svc.cluster.local:26257/ledger?sslmode=require",
              "--spring.datasource.username=craig",
              "--spring.datasource.password=cockroach"
            ]
          volumeMounts:
            - name: client-volume
              mountPath: /cnb/process/config
            - name: log-volume
              mountPath: /workspace/.log
      volumes:
        - name: client-volume
          configMap:
            name: client-configmap-account-plan
            items:
              - key: commands.txt
                path: commands.txt
        - name: log-volume
          emptyDir: {}
